"""
FocusGuard AI - Core Data Models (Enhanced Telemetry)
"""
from dataclasses import dataclass, field
from typing import List, Tuple, Optional


@dataclass
class FaceLandmarksData:
    """Encapsulates raw and normalized landmark coordinates for a detected face."""
    face_detected: bool = False
    pixel_landmarks: List[Tuple[int, int]] = field(default_factory=list)
    normalized_landmarks: List[Tuple[float, float, float]] = field(default_factory=list)
    bbox: Optional[Tuple[int, int, int, int]] = None  # (x, y, w, h)


@dataclass
class EyeMetrics:
    """Telemetry data generated by Eye Tracker Engine."""
    left_ear: float = 0.0
    right_ear: float = 0.0
    avg_ear: float = 0.0
    is_eyes_closed: bool = False
    blink_count: int = 0
    blink_rate_bpm: float = 0.0  # Rolling Blinks Per Minute
    drowsy_alert: bool = False
    drowsy_duration_sec: float = 0.0


@dataclass
class HeadPoseMetrics:
    """Head orientation angles and looking away detection telemetry."""
    pitch: float = 0.0  # Up / Down
    yaw: float = 0.0    # Left / Right
    roll: float = 0.0   # Tilt
    is_looking_away: bool = False
    looking_away_duration_sec: float = 0.0


@dataclass
class FocusTelemetry:
    """Unified realtime focus analytics state with XAI explainability."""
    focus_score: float = 100.0  # 0.0 to 100.0%
    target_score: float = 100.0
    attention_state: str = "FOCUSED"  # FOCUSED, LOOKING_AWAY, DROWSY, NO_FACE
    primary_reason: str = "Optimal Attention"  # Explainable AI reason string
    eye_metrics: EyeMetrics = field(default_factory=EyeMetrics)
    head_pose: HeadPoseMetrics = field(default_factory=HeadPoseMetrics)
